name: "Build openssl interop container from quic-server"

on:
  schedule:
    - cron:  '40 02 * * *'
  workflow_dispatch:

jobs:
  update_quay_container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
         fetch-depth: 0
         ref: feature/quic-server
      - name: "log in to quay.io"
        run: |
          docker login -u openssl-ci+machine -p ${{ secrets.QUAY_IO_PASSWORD }} quay.io
      - name: "Build container"
        run: |
          cd test/quic-openssl-docker/
          docker build -t quay.io/openssl-ci/openssl-quic-interop-server:latest --build-arg OPENSSL_URL=https://github.com/openssl/openssl --build-arg OPENSSL_BRANCH=feature/quic-server .
      - name: "Push to quay"
        run: |
          docker push quay.io/openssl-ci/openssl-quic-interop-server:latest

